create table if not exists payments.debug_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  environment text null,
  level text not null default 'info',
  scope text not null,
  event text not null,
  provider_id text null,
  org_id uuid null,
  checkout_session_id uuid null,
  payment_intent_id uuid null,
  payment_attempt_id uuid null,
  public_token text null,
  data jsonb not null default '{}'::jsonb
);

create index if not exists debug_logs_created_at_idx
  on payments.debug_logs (created_at desc);

create index if not exists debug_logs_public_token_idx
  on payments.debug_logs (public_token);

create index if not exists debug_logs_payment_intent_id_idx
  on payments.debug_logs (payment_intent_id);

create index if not exists debug_logs_payment_attempt_id_idx
  on payments.debug_logs (payment_attempt_id);

comment on table payments.debug_logs is
  'Best-effort internal debug logs for payment orchestration (provider requests/responses, callbacks, webhook routing).';
